/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PurchaseCompletedRouteImport } from './routes/purchaseCompleted'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DetailsDetailsIdRouteImport } from './routes/Details/$detailsId'

const PurchaseCompletedRoute = PurchaseCompletedRouteImport.update({
  id: '/purchaseCompleted',
  path: '/purchaseCompleted',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DetailsDetailsIdRoute = DetailsDetailsIdRouteImport.update({
  id: '/Details/$detailsId',
  path: '/Details/$detailsId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/purchaseCompleted': typeof PurchaseCompletedRoute
  '/Details/$detailsId': typeof DetailsDetailsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/purchaseCompleted': typeof PurchaseCompletedRoute
  '/Details/$detailsId': typeof DetailsDetailsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/purchaseCompleted': typeof PurchaseCompletedRoute
  '/Details/$detailsId': typeof DetailsDetailsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/purchaseCompleted' | '/Details/$detailsId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/purchaseCompleted' | '/Details/$detailsId'
  id: '__root__' | '/' | '/purchaseCompleted' | '/Details/$detailsId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PurchaseCompletedRoute: typeof PurchaseCompletedRoute
  DetailsDetailsIdRoute: typeof DetailsDetailsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/purchaseCompleted': {
      id: '/purchaseCompleted'
      path: '/purchaseCompleted'
      fullPath: '/purchaseCompleted'
      preLoaderRoute: typeof PurchaseCompletedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Details/$detailsId': {
      id: '/Details/$detailsId'
      path: '/Details/$detailsId'
      fullPath: '/Details/$detailsId'
      preLoaderRoute: typeof DetailsDetailsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PurchaseCompletedRoute: PurchaseCompletedRoute,
  DetailsDetailsIdRoute: DetailsDetailsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
